
  services:
    app: 
      image: stream-diffusion:latest
      build:
        context: ./
        dockerfile: ./Dockerfile
      volumes:
        - ./:/home/ubuntu/streamdiffusion
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /mnt/wslg:/mnt/wslg
      environment:
        # WSLg
        - DISPLAY=$DISPLAY
        - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
        - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
        - PULSE_SERVER=$PULSE_SERVER
        # GPUを使うための設定
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
      command: sleep infinity
      deploy:
        resources:
          reservations:
            devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [compute, utility]
      